### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by vermamanjeet** [CognirelTech/Quillpad-Server#3]
i tried to run on window 7 , window 10 and Ubuntu 16.04 but no success 
i window it give **dll** error but what type of **dll** missing not a name of **dll** so not able to get solve that one
another on Ubuntu its freeze after loading **primary rule for Hindi** after some retry it gonna automatically stop after loading **primary rule for Hindi** and return to type new command

i tried on 2 PC with all 3 OS but both have same result on window and Ubuntu
also tried in vmware 12.. 
**is this work in vmware  ????** 
**what type of dll is missing on window  ????**
**why it freeze and stope in ubuntu ???**
help me to solve this........

![screenshot from 2017-02-03 10-31-41](https://cloud.githubusercontent.com/assets/25535664/22604005/9611a368-ea6f-11e6-8e34-e927f9c6e761.png)
![screenshot from 2017-02-03 10-27-51](https://cloud.githubusercontent.com/assets/25535664/22604009/9cc88726-ea6f-11e6-9a14-98843dbc4726.png)

**Comment by mknverma** [comment]
is this work in vmware ????
**......yes**
what type of dll is missing on window ????
**...... msvcr110.dll and libexpat.dll**

**Comment by sharathpuranik** [comment]
@vermamanjeet It is not freezing in Ubuntu. Its a cherrpy server and it will continue running. 

You should setup Quillpad as a service under [supervisor](https://www.digitalocean.com/community/tutorials/how-to-install-and-manage-supervisor-on-ubuntu-and-debian-vps) so that the server runs in the background or run the server in a [screen](http://www.tecmint.com/screen-command-examples-to-manage-linux-terminals/) session.
